AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
