AllCops:
  DisplayCopNames: true
  ExtraDetails: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
