sudo: false
language: ruby
os:
  - linux
  - osx
rvm:
  - 2.3.3
  - 2.4.0
  - ruby-head
matrix:
  include:
  - os: osx
    rvm: 2.2.5
  - os: linux
    rvm: 2.2.6
  allow_failures:
    - rvm: ruby-head
install:
  - gem cleanup bundler
  - gem install bundler -v 1.13.7
  - bundle install --jobs=3 --retry=3
