sudo: false
language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.10
  - 2.3.3
  - ruby-head
matrix:
  include:
  - os: osx
    rvm: 2.2.5
  - os: linux
    rvm: 2.2.6
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler -v 1.13.6
install:
  - bundle install --jobs=3 --retry=3
