sudo: false
language: ruby
os:
  - linux
  - osx
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
install:
  - gem cleanup bundler
  - gem install bundler -v 2.1.4
  - bundle install --jobs=3 --retry=3
